GET https://bad-api-assignment.reaktor.com/v2/products/facemasks

###

GET https://bad-api-assignment.reaktor.com/v2/products/gloves

###

GET https://bad-api-assignment.reaktor.com/v2/products/beanies

###
GET https://bad-api-assignment.reaktor.com/v2/availability/umpante
###
GET https://bad-api-assignment.reaktor.com/v2/availability/juuran
###
GET http://localhost:3001/api/facemasks